server:
  error:
    include-exception: false
    include-stacktrace: never
management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  health:
    probes:
      enabled: true
okta:
  oauth2:
    issuer: https://dev-991339.okta.com/oauth2/default
    client-id: 0oaclzf69sveYfurb4x6
    groups-claim: roles
    audience: api://default
