version: '3.3'
services:
  dev_postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: verysecure
      POSTGRES_USER: dev
      POSTGRES_DB: cocktails
    ports:
      - "54321:5432"
    restart: always
