on: [push, pull_request]
name: "Build cocktail app"

jobs:
  build-and-test:
    env:
      MAVEN_REPO_PATH: ".m2/repository"
      MAVEN_OPTS: "-Dmaven.repo.local=${MAVEN_REPO_PATH}"
    runs-on: ubuntu-latest
    container: openjdk:14-jdk-alpine
    services:
      postgres:
        image: postgres:12.2-alpine
        env:
          POSTGRES_PASSWORD: verysecure
          POSTGRES_USER: dev
          POSTGRES_DB: cocktails
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Caching
        uses: actions/cache@v1
        with:
          path: "${MAVEN_REPO_PATH}"
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup CI config
        run: cp ci.properties no-docker-tests.properties
      - name: Compile
        run: ./mvnw --batch-mode clean compile
      - name: Test
        run: ./mvnw --batch-mode -P no-docker verify
      - name: Upload coverage data to codecov.io
        run:
          - apk add bash curl
          - curl -s https://codecov.io/bash > .codecov
          - chmod +x .codecov
          - ./.codecov
